<a href="https://colab.research.google.com/github/AnimeshGalande/NLP/blob/master/Fake_New_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
from google.colab import files
upload = files.upload()

Saving X_data.csv to X_data.csv


In [ ]:
!nvidia-smi

Fri May 14 05:34:14 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
from google.colab import files
upload = files.upload()

Saving y_data.csv to y_data.csv


In [ ]:
X_data = pd.read_csv('X_data.csv')
X_data

Unnamed: 0                                              title
0               0  House Dem Aide: We Didn’t Even See Comey’s Let...
1               1  FLYNN: Hillary Clinton, Big Woman on Campus - ...
2               2                  Why the Truth Might Get You Fired
3               3  15 Civilians Killed In Single US Airstrike Hav...
4               4  Iranian woman jailed for fictional unpublished...
...           ...                                                ...
18280       18280  Rapper T.I.: Trump a ’Poster Child For White S...
18281       18281  N.F.L. Playoffs: Schedule, Matchups and Odds -...
18282       18282  Macy’s Is Said to Receive Takeover Approach by...
18283       18283  NATO, Russia To Hold Parallel Exercises In Bal...
18284       18284                          What Keeps the F-35 Alive

[18285 rows x 2 columns]

In [ ]:
y_data = pd.read_csv('y_data.csv')
y_data

Unnamed: 0  label
0               0      1
1               1      0
2               2      1
3               3      1
4               4      1
...           ...    ...
18280       18280      0
18281       18281      0
18282       18282      0
18283       18283      1
18284       18284      1

[18285 rows x 2 columns]

In [ ]:
y_data = y_data['label']
y_data.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [ ]:
X_data =X_data['title']
X_data.head()

0    House Dem Aide: We Didn’t Even See Comey’s Let...
1    FLYNN: Hillary Clinton, Big Woman on Campus - ...
2                    Why the Truth Might Get You Fired
3    15 Civilians Killed In Single US Airstrike Hav...
4    Iranian woman jailed for fictional unpublished...
Name: title, dtype: object

In [ ]:
import re 
import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
nltk.download('stopwords')
from nltk import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


True

In [ ]:
Lemetizer = WordNetLemmatizer()

In [ ]:
corpus = []
for i in range(len(X_data)):
  sentence = re.sub('[^a-zA-Z]',' ',X_data[i])
  sentence = sentence.lower()
  sentence = nltk.word_tokenize(sentence)
  sentence = [word for word in sentence if word not in set(stopwords.words('english'))]
  sentence = [Lemetizer.lemmatize(word)for word in sentence]
  corpus.append(' '.join(sentence))
corpus

['house dem aide even see comey letter jason chaffetz tweeted',
 'flynn hillary clinton big woman campus breitbart',
 'truth might get fired',
 'civilian killed single u airstrike identified',
 'iranian woman jailed fictional unpublished story woman stoned death adultery',
 'jackie mason hollywood would love trump bombed north korea lack trans bathroom exclusive video breitbart',
 'beno hamon win french socialist party presidential nomination new york time',
 'back channel plan ukraine russia courtesy trump associate new york time',
 'obama organizing action partner soros linked indivisible disrupt trump agenda',
 'bbc comedy sketch real housewife isi cause outrage',
 'russian researcher discover secret nazi military base treasure hunter arctic photo',
 'u official see link trump russia',
 'yes paid government troll social medium blog forum website',
 'major league soccer argentine find home success new york time',
 'well fargo chief abruptly step new york time',
 'anonymous donor pay 

In [ ]:
len(corpus)

18285

In [ ]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
dim = 10000

In [ ]:
onehot = []
for i in range(len(corpus)):
  onehot.append(one_hot(corpus[i],dim))

In [ ]:
print(onehot)

[[5106, 9984, 2129, 9637, 3535, 4470, 9252, 3295, 8877, 7049], [6506, 1078, 7669, 5213, 3736, 5054, 330], [3154, 594, 4827, 3605], [2549, 3915, 8578, 5869, 5696, 5865], [4623, 3736, 5340, 244, 7396, 1764, 3736, 5810, 2221, 5836], [814, 2512, 6428, 4785, 1842, 4407, 3585, 7036, 9554, 5746, 2924, 5396, 4445, 4672, 330], [1342, 2990, 6042, 4503, 1064, 8753, 9482, 2923, 5992, 1720, 6807], [4703, 4568, 7446, 7216, 6196, 1522, 4407, 9129, 5992, 1720, 6807], [1182, 9171, 1808, 1163, 5892, 2958, 224, 3438, 4407, 4849], [1252, 7079, 9316, 7101, 9780, 376, 2757, 4143], [4436, 244, 2264, 2891, 2310, 1428, 674, 4065, 6510, 8681, 3538], [5869, 8431, 3535, 9292, 4407, 6196], [4445, 495, 9885, 3427, 5439, 6777, 3989, 6635, 1621], [5440, 1798, 7693, 2184, 1966, 1982, 4226, 5992, 1720, 6807], [1943, 7741, 9668, 2244, 1541, 5992, 1720, 6807], [5840, 1450, 4746, 7809, 7997, 9592, 846, 5970, 7613, 6244], [5088, 5505, 1078], [5803, 7816, 9351, 2528, 4407, 7456, 8505, 330], [6636, 2088, 7669, 645, 5230, 356

In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM,Dense,Embedding
from tensorflow.keras.models import Sequential

In [ ]:
padded = pad_sequences(onehot,padding='pre')
print(padded[0])

[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0 5106 9984 2129 9637 3535
 4470 9252 3295 8877 7049]


In [ ]:
padded.shape

(18285, 47)

In [ ]:
import numpy as np
X_final = np.array(padded)
y_final = np.array(y_data)

[[   0    0    0 ... 3295 8877 7049]
 [   0    0    0 ... 3736 5054  330]
 [   0    0    0 ...  594 4827 3605]
 ...
 [   0    0    0 ... 5992 1720 6807]
 [   0    0    0 ... 9101 7574 4477]
 [   0    0    0 ... 6834 1318 6520]] [1 0 1 ... 0 1 1]


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size = 0.3, random_state = 42)

In [ ]:
X_train[1:5]

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0, 2744, 9362, 5692, 3095, 5916, 2267, 9697, 4426,  440,
        4407, 4697,  330],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0, 1078,
        9300, 3432,  472],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0, 8639, 2422, 2264, 2716, 9836, 8216, 2578,
        5992, 1720, 6807],
       [   0,    0,    0,    0,

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=dim,output_dim=20,input_length=padded.shape[1]))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 47, 20)            200000    
_________________________________________________________________
lstm (LSTM)                  (None, 100)               48400     
_________________________________________________________________
dense (Dense)                (None, 1)                 101       
Total params: 248,501
Trainable params: 248,501
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64)

Epoch 1/10
200/200 [==============================] - 35s 13ms/step - loss: 0.5173 - accuracy: 0.7192 - val_loss: 0.2017 - val_accuracy: 0.9154
Epoch 2/10
200/200 [==============================] - 2s 10ms/step - loss: 0.1323 - accuracy: 0.9496 - val_loss: 0.2188 - val_accuracy: 0.9191
Epoch 3/10
200/200 [==============================] - 2s 10ms/step - loss: 0.0686 - accuracy: 0.9763 - val_loss: 0.2484 - val_accuracy: 0.9182
Epoch 4/10
200/200 [==============================] - 2s 10ms/step - loss: 0.0317 - accuracy: 0.9902 - val_loss: 0.2844 - val_accuracy: 0.9189
Epoch 5/10
200/200 [==============================] - 2s 10ms/step - loss: 0.0147 - accuracy: 0.9965 - val_loss: 0.3928 - val_accuracy: 0.9154
Epoch 6/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0141 - accuracy: 0.9965 - val_loss: 0.3229 - val_accuracy: 0.9109
Epoch 7/10
200/200 [==============================] - 2s 10ms/step - loss: 0.0057 - accuracy: 0.9990 - val_loss: 0.4074 - val_accuracy: 0.9163

In [ ]:
y_pred = model.predict_classes(X_test)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [ ]:
y_pred

array([[1],
       [0],
       [0],
       ...,
       [1],
       [0],
       [1]], dtype=int32)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [ ]:
confusion_matrix(y_test,y_pred)

array([[2818,  289],
       [ 183, 2196]])

In [ ]:
accuracy_score(y_test,y_pred)

0.9139628144367481

In [ ]:
model = Sequential()
model.add(Embedding(input_dim=dim,output_dim=20,input_length=padded.shape[1]))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=10,batch_size=64)
y_pred = model.predict_classes(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Epoch 1/10
200/200 [==============================] - 3s 9ms/step - loss: 0.5078 - accuracy: 0.7192
Epoch 2/10
200/200 [==============================] - 2s 9ms/step - loss: 0.1339 - accuracy: 0.9500
Epoch 3/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0736 - accuracy: 0.9753
Epoch 4/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0406 - accuracy: 0.9890
Epoch 5/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0206 - accuracy: 0.9945
Epoch 6/10
200/200 [==============================] - 2s 9ms/step - loss: 0.0136 - accuracy: 0.9968
Epoch 7/10
200/200 [==============================] - 2s 8ms/step - loss: 0.0144 - accuracy: 0.9961
Epoch 8/10
200/200 [==============================] - 2s 8ms/step - loss: 0.0056 - accuracy: 0.9989
Epoch 9/10
200/200 [==============================] - 2s 8ms/step - loss: 0.0061 - accuracy: 0.9985
Epoch 10/10
200/200 [==============================] - 2s 8ms/step - loss: 0.0020 - accuracy: 0.9994

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


0.8922712358731316
[[2909  198]
 [ 393 1986]]


In [ ]:
model = Sequential()
model.add(Embedding(input_dim=dim,output_dim=40,input_length=padded.shape[1]))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(X_train,y_train,epochs=10,batch_size=64)
y_pred = model.predict_classes(X_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

Epoch 1/10
200/200 [==============================] - 4s 11ms/step - loss: 0.4664 - accuracy: 0.7624
Epoch 2/10
200/200 [==============================] - 2s 11ms/step - loss: 0.1199 - accuracy: 0.9564
Epoch 3/10
200/200 [==============================] - 2s 11ms/step - loss: 0.0510 - accuracy: 0.9841
Epoch 4/10
200/200 [==============================] - 2s 11ms/step - loss: 0.0314 - accuracy: 0.9909
Epoch 5/10
200/200 [==============================] - 2s 11ms/step - loss: 0.0144 - accuracy: 0.9961
Epoch 6/10
200/200 [==============================] - 2s 11ms/step - loss: 0.0072 - accuracy: 0.9985
Epoch 7/10
200/200 [==============================] - 2s 11ms/step - loss: 0.0059 - accuracy: 0.9992
Epoch 8/10
200/200 [==============================] - 2s 11ms/step - loss: 0.0025 - accuracy: 0.9995
Epoch 9/10
200/200 [==============================] - 2s 11ms/step - loss: 4.6984e-04 - accuracy: 1.0000
Epoch 10/10
200/200 [==============================] - 2s 11ms/step - loss: 1.2707e-04 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


0.9134159679183376
[[2825  282]
 [ 193 2186]]
