<a href="https://colab.research.google.com/github/AnimeshGalande/NLP/blob/master/Word_Embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from tensorflow.keras.preprocessing.text import one_hot

In [20]:
sentences =  ["I want to dance.",
"I like to eat",
"Dreams may come true."	,
"Apple is a red colour fruit.",
"Pineapple is a fruit.",
"Fruit can be used for making juice.",
"We can eat fruit"]
sentences

['I want to dance.',
 'I like to eat',
 'Dreams may come true.',
 'Apple is a red colour fruit.',
 'Pineapple is a fruit.',
 'Fruit can be used for making juice.',
 'We can eat fruit']

In [15]:
#vocabulary size 
voc_size = 10000

One hot representation

In [21]:
onehot_rep = [one_hot(input_text=words, n = voc_size)for words in sentences]
print(onehot_rep)

[[56, 8300, 761, 1090], [56, 6136, 761, 8557], [9819, 9107, 3770, 4900], [3418, 3038, 1112, 1020, 6540, 2697], [6540, 3038, 1112, 2697], [2697, 8979, 9391, 4174, 8254, 8630, 9167], [1877, 8979, 8557, 2697]]


In [19]:
 from tensorflow.keras.layers import Embedding
 from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [22]:
import numpy as np

In [25]:
sent_len = 10
#For padding we actually require similar length sentence . so in case sentence is smaller it have 0 until sentence begins/end depending on pre /post
embedd = pad_sequences(onehot_rep,sent_len,padding= 'pre')
print(embedd)

[[   0    0    0    0    0    0   56 8300  761 1090]
 [   0    0    0    0    0    0   56 6136  761 8557]
 [   0    0    0    0    0    0 9819 9107 3770 4900]
 [   0    0    0    0 3418 3038 1112 1020 6540 2697]
 [   0    0    0    0    0    0 6540 3038 1112 2697]
 [   0    0    0 2697 8979 9391 4174 8254 8630 9167]
 [   0    0    0    0    0    0 1877 8979 8557 2697]]


In [26]:
dim = 15

In [27]:
model = Sequential()
model.add(Embedding(input_dim = voc_size,output_dim=dim,input_length=sent_len))
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 10, 15)            150000    
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [29]:
model.predict(embedd)

array([[[-0.04235889,  0.02396578,  0.00836738, ...,  0.0191418 ,
         -0.01327976, -0.00097411],
        [-0.04235889,  0.02396578,  0.00836738, ...,  0.0191418 ,
         -0.01327976, -0.00097411],
        [-0.04235889,  0.02396578,  0.00836738, ...,  0.0191418 ,
         -0.01327976, -0.00097411],
        ...,
        [-0.0294969 , -0.00297923, -0.01715159, ...,  0.03073126,
         -0.01583539,  0.01879381],
        [ 0.03888226,  0.03082657, -0.04344118, ..., -0.00820681,
         -0.04497954, -0.01642162],
        [-0.02526004,  0.00537413, -0.04939215, ...,  0.03696654,
         -0.00935436,  0.00031392]],

       [[-0.04235889,  0.02396578,  0.00836738, ...,  0.0191418 ,
         -0.01327976, -0.00097411],
        [-0.04235889,  0.02396578,  0.00836738, ...,  0.0191418 ,
         -0.01327976, -0.00097411],
        [-0.04235889,  0.02396578,  0.00836738, ...,  0.0191418 ,
         -0.01327976, -0.00097411],
        ...,
        [-0.03844581,  0.02655523, -0.01364971, ..., -